// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utohufqdbpyompkxpusr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0b2h1ZnFkYnB5b21wa3hwdXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTQ5NjMsImV4cCI6MjA3MTEzMDk2M30.HOSRKERwZ9XeBmiOf8FfDZEmb3co4_mKdyHwD1Uygg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});